language: python

os:
  - linux

dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

sudo: false

addons:
  apt:
    packages:
      - xvfb

env:
  global:
    # Doctr deploy key for OpenGeoVis/omfvista
    - secure: "k1J+bTbiLXFCzFJ7AVsFtEtnk+DlEl6J61WK5Ez0fN3gI5i/ZtF6MDLl5sM43igWCs4OVF6jUnmGLZXqHBg9BItvOztWk4BwNu0cawT7c8miv5jn7nIcT1mP5xG+14mLVsWKsp5aADUjSel2QXINHRp9VW+0npsaY7QVLpa9qtfnADPoitdFO3H90/wE+4ZEvXObIUuj7bXul/bz1Rr46Wmif5li/RpMTWLzp5EYDrHnNjHdMP6pdI+x+jfg+1Tw7Cstjsswe2NMRe4gTICyQ+tVJxHp4gQvcRBLoQfdGgsC7orBGNdyhAzSaDJ1d80ul4e30+DDYDMiQ8lSL9b7U/w9AbCMmyEeaNm++nbSFbNtHOLJIAiHJ2MrkheLLYwMo0ELOwiXC/dE23d4VTPKg9fuAR5yRBjKbcWJiGSLOcbToaMdfku4ZhJvJVbvftPNyjqDjEPFaLUw+LEAHCuIesWpV1muezW6MSgf06zispfQP+swJof2M4uaI98/EBZ960uuBN6iNxapgTvz17EkkPnGR8FzmDZ5eYqnLR8R++skSjCP3S3Vnkt27kUisM//UEPAcXWzHrSTd3277HxykQoRGXTmGm9kR01IsGSFcZKnwSCe/ecPjXgIevK5M17sDipFQry3MVFrhdSsypseY5S+s7jl29wH2qsoVHXhzSQ="

before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - which Xvfb
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # - ls -l /etc/init.d/
  # - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh

install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install pytest-cov
  - pip install -e .
  - pip install PyQt5 pytest-qt matplotlib;
  - pip install nbval ipython ipywidgets; # For testing the notebooks
  - pip install imageio-ffmpeg
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
        pip install -r docs/requirements.txt;
    fi
  - which python
  - python -c "import vtk; print(vtk.VTK_VERSION)"

script:
  - coverage run tests/__main__.py
  - python tests/__main__.py
  # Now make sure notebooks are running
  - pytest -v --nbval-lax --current-env --disable-warnings Example.ipynb;
  - codecov --token=1dc88395-9612-4ef9-9574-62c035d25908
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      cd ./docs;
      make html;
      set -e;
      make html;
      cd ..;
      doctr deploy --built-docs ./docs/_build/html/ .;
    fi

notifications:
  email:
    recipients:
    - info@opengeovis.org
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    repo: OpenGeoVis/omfvista
    branch: master
    tags: true
    python: 3.7
