language: python
os:
  - linux
python:
  - 2.7
  - 3.6
sudo: false
install:
  - python setup.py install
script:
  - python tests/test.py
notifications:
  email:
    recipients:
    - info@pvgeo.org
    on_success: never
    on_failure: never
