# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build: off

environment:
  matrix:
    # VTK is incompatible with windows python 2.7
    # this is because vtk-v8.x.x requres c++11 which is incompatible
    # - PYTHON_VERSION: 2.7
    #   CONDA: C:\Miniconda

    - PYTHON_VERSION: 3.6
      CONDA: C:\Miniconda36

image: Visual Studio 2015

platform:
- x64
- x86

init:
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:PLATFORM

install:
  # Load the conda root environment, configure and install some packages
  - '"%CONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Upgrade pip
  - python -m pip install --upgrade pip
  # Handle VTK if archetecture requires conda, else let setup.py install via pip
  - cmd: if "%PLATFORM%" == "x86" (conda install vtk) else (echo "setup.py should install VTK")
  # Install omfvista
  - python setup.py install

test_script:
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - python -c "import pyvista; print(pyvista.__version__)"
  - python -c "import omfvista; print('omfvista Version ', omfvista.__version__)"
  - python tests/__main__.py
